Repository paritytech/substrate-light-ui, pull requests merged in 2019-10, with the labels that each got.

#578 Feat: TxQueue Cancel Observable + Alert timeout
  packages/accounts-app/src/Staking/Bond.tsx
  packages/accounts-app/src/Validators/FinalConfirmation.tsx
  packages/light-apps/src/App.tsx
  packages/light-apps/src/Content/Content.tsx
  packages/light-apps/src/Signer/Signer.tsx
  packages/light-apps/src/TxQueueNotifier/TxQueueNotifier.tsx
  packages/transfer-app/src/Transfer.tsx
  packages/ui-common/src/AlertsContext.tsx
  packages/ui-common/src/TxQueueContext.tsx
  packages/ui-components/src/Alert.tsx
Labels: A8-looksgood

#577 feat: mnemonic phrase rewrite
  packages/light-apps/src/AddAccount/AddAccount.tsx
  packages/light-apps/src/AddAccount/Create.tsx
  packages/light-apps/src/AddAccount/Create/CreateAccount.tsx
  packages/light-apps/src/AddAccount/Create/index.tsx
  packages/light-apps/src/AddAccount/Create/subComponents.tsx
  packages/light-apps/src/AddAccount/types.ts
  packages/light-apps/src/AddAccount/util.ts
  packages/light-apps/src/Onboarding/AccountsSetup.tsx
  packages/light-apps/src/Onboarding/ShowValidators.tsx
  packages/ui-components/src/Labelled.tsx
  packages/ui-components/src/MnemonicPhraseList.tsx
  packages/ui-components/src/MnemonicRewriteParts.tsx
  packages/ui-components/src/index.ts
  packages/ui-components/stories/MnemonicPhraseList.stories.tsx
Labels: A0-pleasereview

#579 fix: quick fix getting accounts from bonding, get ready for design fixes
  packages/accounts-app/src/Staking/Bond.tsx
  packages/ui-components/src/Alert.tsx
  packages/ui-components/src/Card.tsx
  packages/ui-components/src/Shared.styles.ts
  packages/ui-components/src/StyleProps.tsx
Labels: A2-insubstantial, A8-looksgood

#582 fix #350: show active tab
  packages/light-apps/src/IdentityHeader/IdentityHeader.tsx
Labels: A0-pleasereview, A2-insubstantial

#576 chore: Update to latest @polkadot/api beta
  package.json
  packages/accounts-app/src/Accounts/BalanceOverview.tsx
  packages/accounts-app/src/Staking/Bond.tsx
  packages/accounts-app/src/Staking/Setup.tsx
  packages/accounts-app/src/Validators/FinalConfirmation.tsx
  packages/accounts-app/src/Validators/ValidatorListHeader.tsx
  packages/governance-app/src/Democracy/ProposalRow.tsx
  packages/governance-app/src/Democracy/Referenda.tsx
  packages/governance-app/src/Democracy/ReferendumRow.tsx
  packages/light-apps/src/App.tsx
  packages/light-apps/src/IdentityHeader/IdentityHeader.styles.tsx
  packages/light-apps/src/IdentityHeader/IdentityHeader.tsx
  packages/light-apps/src/Onboarding/AccountsSetup.tsx
  packages/transfer-app/src/SendBalance/SendBalance.tsx
  packages/transfer-app/src/SendBalance/validate.ts
  packages/ui-common/package.json
  packages/ui-common/src/StakingContext.tsx
  packages/ui-common/src/util/validate.ts
  packages/ui-components/src/Shared.styles.ts
  packages/ui-components/src/fromApps/Dropdown.tsx
  packages/ui-components/src/fromApps/Icon.tsx
  packages/ui-components/src/fromApps/InputAddress.tsx
  packages/ui-components/src/fromApps/LabelHelp.tsx
  packages/ui-components/src/fromApps/Labelled.tsx
  packages/ui-components/src/fromApps/README.MD
  packages/ui-components/src/fromApps/Tooltip.tsx
  packages/ui-components/src/fromApps/index.ts
  packages/ui-components/src/fromApps/types.ts
  packages/ui-components/src/fromApps/util/classes.ts
  packages/ui-components/src/fromApps/util/getAddressMeta.ts
  packages/ui-components/src/fromApps/util/getAddressName.ts
  packages/ui-components/src/fromApps/util/getAddressTags.ts
  packages/ui-components/src/fromApps/util/index.ts
  packages/ui-components/src/fromApps/util/isTreasuryProposalVote.ts
  packages/ui-components/src/fromApps/util/toAddress.ts
  packages/ui-components/src/fromApps/util/types.ts
  packages/ui-components/src/index.ts
  packages/ui-components/src/stateful/Balance.tsx
  packages/ui-components/src/stateful/InputAddress.tsx
  packages/ui-components/src/stateful/index.ts
  yarn.lock
Labels: A0-pleasereview

#605 fix: Make all console.error disappear
  packages/accounts-app/src/Validators/ValidatorsList.tsx
  packages/ui-components/src/Alert.tsx
  packages/ui-components/src/BalanceDisplay.tsx
  packages/ui-components/src/stateful/InputAddress.tsx
Labels: A8-looksgood

#581 Redesign transfer app
  packages/accounts-app/src/Accounts/AccountsOverviewCard.tsx
  packages/accounts-app/src/Validators/ValidatorRow.tsx
  packages/light-apps/src/Content/Content.tsx
  packages/light-apps/src/IdentityHeader/IdentityHeader.tsx
  packages/transfer-app/src/SendBalance/SendBalance.tsx
  packages/transfer-app/src/SendBalance/Validation.tsx
  packages/transfer-app/src/SendBalance/validate.ts
  packages/transfer-app/src/Transfer.tsx
  packages/transfer-app/src/TxQueue.tsx
  packages/transfer-app/src/index.ts
  packages/ui-common/src/TxQueueContext.tsx
  packages/ui-components/src/Alert.tsx
  packages/ui-components/src/Fab.tsx
  packages/ui-components/src/Modal.tsx
  packages/ui-components/src/index.ts
  packages/ui-components/stories/Fab.stories.tsx
Labels: A8-looksgood

#623 chore(deps): Update all polkadot packages
  package.json
  packages/light-apps/package.json
  packages/ui-common/package.json
  packages/ui-components/package.json
  yarn.lock
Labels: A0-pleasereview

#624 chore(dev-deps): Bump all storybooks at once
  packages/ui-components/package.json
  yarn.lock
Labels: A0-pleasereview
