Repository paritytech/substrate-light-ui, pull requests merged in 2019-08, with the labels that each got.

#434 Feat(Validators): show validators list and nominate
  package.json
  packages/accounts-app/src/Accounts/AccountOverviewDetailed.tsx
  packages/accounts-app/src/Accounts/AccountsOverviewCard.tsx
  packages/accounts-app/src/Accounts/AccountsOverviewDetailed.tsx
  packages/accounts-app/src/Accounts/BalanceOverview.tsx
  packages/accounts-app/src/Accounts/Staking/Bond.tsx
  packages/accounts-app/src/Accounts/Staking/Nominate.tsx
  packages/accounts-app/src/Accounts/Staking/StakingOptions.tsx
  packages/accounts-app/src/Accounts/index.tsx
  packages/accounts-app/src/Staking/Bond.tsx
  packages/accounts-app/src/Staking/Setup.tsx
  packages/accounts-app/src/Staking/StakingOptions.tsx
  packages/accounts-app/src/Staking/index.tsx
  packages/accounts-app/src/Validation.tsx
  packages/accounts-app/src/Validators/ConfirmNominationDialog.tsx
  packages/accounts-app/src/Validators/FinalConfirmation.tsx
  packages/accounts-app/src/Validators/SelectNominateWith.tsx
  packages/accounts-app/src/Validators/ValidatorListHeader.tsx
  packages/accounts-app/src/Validators/ValidatorRow.tsx
  packages/accounts-app/src/Validators/ValidatorsList.tsx
  packages/accounts-app/src/Validators/index.tsx
  packages/accounts-app/src/constants.ts
  packages/accounts-app/src/index.ts
  packages/accounts-app/src/index.tsx
  packages/accounts-app/src/types.ts
  packages/light-apps/package.json
  packages/light-apps/src/App.tsx
  packages/light-apps/src/Content/Content.tsx
  packages/ui-common/package.json
  packages/ui-common/src/AlertsContext.tsx
  packages/ui-common/src/ContextGate.tsx
  packages/ui-common/src/StakingContext.tsx
  packages/ui-common/src/index.ts
  packages/ui-common/src/types.ts
  packages/ui-common/src/util/validate.ts
  packages/ui-components/package.json
  packages/ui-components/src/Address.tsx
  packages/ui-components/src/Alert.tsx
  packages/ui-components/src/BalanceDisplay.tsx
  packages/ui-components/src/Shared.styles.ts
  packages/ui-components/src/StyleProps.tsx
  packages/ui-components/src/TxSummary.tsx
  packages/ui-components/src/stateful/AddressSummary/AddressSummary.tsx
  yarn.lock
Labels: A0-pleasereview

#477 Update README.md
  README.md
Labels: A0-pleasereview

#526 chore: Update all polkadot deps
  package.json
  packages/accounts-app/src/Staking/Setup.tsx
  packages/light-apps/package.json
  packages/light-apps/src/IdentityHeader/IdentityHeader.styles.tsx
  packages/light-apps/src/IdentityHeader/IdentityHeader.tsx
  packages/light-apps/src/TopBar/TopBar.tsx
  packages/transfer-app/src/SendBalance/SendBalance.tsx
  packages/transfer-app/src/Transfer.styles.tsx
  packages/ui-common/package.json
  packages/ui-common/src/ContextGate.tsx
  packages/ui-components/package.json
  packages/ui-components/src/fromApps/Dropdown.tsx
  packages/ui-components/src/fromApps/Icon.tsx
  packages/ui-components/src/fromApps/InputAddress.tsx
  packages/ui-components/src/fromApps/LabelHelp.tsx
  packages/ui-components/src/fromApps/Labelled.tsx
  packages/ui-components/src/fromApps/README.MD
  packages/ui-components/src/fromApps/Tooltip.tsx
  packages/ui-components/src/fromApps/index.ts
  packages/ui-components/src/fromApps/types.ts
  packages/ui-components/src/fromApps/util/classes.ts
  packages/ui-components/src/fromApps/util/getAddressMeta.ts
  packages/ui-components/src/fromApps/util/getAddressName.ts
  packages/ui-components/src/fromApps/util/getAddressTags.ts
  packages/ui-components/src/fromApps/util/index.ts
  packages/ui-components/src/fromApps/util/isTreasuryProposalVote.ts
  packages/ui-components/src/fromApps/util/toAddress.ts
  packages/ui-components/src/fromApps/util/types.ts
  packages/ui-components/src/index.ts
  packages/ui-components/src/stateful/Balance.tsx
  yarn.lock
Labels: A0-pleasereview

#528 feat: breadcrumbs component
  package.json
  packages/light-apps/src/TopBar/TopBar.styles.tsx
  packages/ui-components/src/Breadcrumbs.tsx
  packages/ui-components/src/Circle.tsx
  packages/ui-components/src/index.ts
  packages/ui-components/stories/Breadcrumbs.stories.tsx
  tslint.json
  yarn.lock
Labels: @ui-components

#289 Bump Storybook to 5.0
  packages/ui-components/.storybook/webpack.config.js
  packages/ui-components/package.json
  yarn.lock
Labels: A0-pleasereview, M5-dependencies
