Repository paritytech/substrate-light-ui, pull requests merged in 2019-03, with the labels that each got.

#139 chore: update all @polkadot/* at once
  package.json
  packages/light-apps/package.json
  packages/ui-api/package.json
  packages/ui-components/package.json
  yarn.lock
Labels: A0-pleasereview

#138 fix: remove react warning message for controlled components
  packages/light-apps/src/Onboarding/CreateNewAccountScreen.tsx
Labels: A8-looksgood

#158 Contributing.md
  CONTRIBUTING.md
  README.md
Labels: A3-inprogress

#30 Storybook First Pass
  .gitignore
  .travis.yml
  package.json
  packages/light-apps/src/App.tsx
  packages/ui-components/.storybook/addons.ts
  packages/ui-components/.storybook/config.ts
  packages/ui-components/.storybook/webpack.config.js
  packages/ui-components/package.json
  packages/ui-components/src/Accordion.tsx
  packages/ui-components/src/Address.tsx
  packages/ui-components/src/AddressSummary/AddressSummary.tsx
  packages/ui-components/src/AddressSummary/types.ts
  packages/ui-components/src/Balance.tsx
  packages/ui-components/src/Card.tsx
  packages/ui-components/src/CopyButton.tsx
  packages/ui-components/src/Input.tsx
  packages/ui-components/src/InputFile.tsx
  packages/ui-components/src/NavButton.tsx
  packages/ui-components/src/NavLink.tsx
  packages/ui-components/src/Segment.tsx
  packages/ui-components/src/Shared.styles.ts
  packages/ui-components/src/StyleProps.tsx
  packages/ui-components/src/WalletCard.tsx
  packages/ui-components/src/globalStyle.tsx
  packages/ui-components/src/index.ts
  packages/ui-components/stories/Accordion.stories.tsx
  packages/ui-components/stories/Address.stories.tsx
  packages/ui-components/stories/AddressSummary.stories.tsx
  packages/ui-components/stories/Input.stories.tsx
  packages/ui-components/stories/InputFile.stories.tsx
  packages/ui-components/stories/NavButton.stories.tsx
  packages/ui-components/stories/NavLink.stories.tsx
  packages/ui-components/stories/WalletCard.stories.tsx
  packages/ui-components/stories/customDecorators/index.ts
  packages/ui-components/stories/customDecorators/withMemoryRouter.tsx
  packages/ui-components/stories/customDecorators/withTheme.tsx
  packages/ui-components/stories/theme.stories.tsx
  packages/ui-components/stories/types.ts
  packages/ui-components/tsconfig.json
  yarn.lock
Labels: A0-pleasereview

#166 fix storybook-deploy
  package.json
Labels: A8-looksgood

#173 chore(deps): bump all @polkadot deps
  packages/light-apps/package.json
  packages/ui-api/package.json
  packages/ui-components/package.json
  yarn.lock
Labels: A8-looksgood

#205 chore: Update travis.yml
  .travis.yml
  package.json
  packages/ui-components/package.json
  yarn.lock
Labels: A0-pleasereview

#215 fix: whole app is not flickering anymore
  CONTRIBUTING.md
  packages/light-apps/package.json
  packages/light-apps/src/IdentityCard/IdentityCard.tsx
  packages/ui-api/package.json
  packages/ui-api/src/Subscribe.tsx
  packages/ui-api/src/index.ts
  yarn.lock
Labels: A0-pleasereview

#216 fix(transfer-app): Make the recipient clickable
  packages/transfer-app/src/Saved.tsx
  packages/transfer-app/src/SendBalance.tsx
Labels: A8-looksgood
