Repository paritytech/substrate-light-ui, pull requests merged in 2019-05, with the labels that each got.

#302 Add Ability to Select Which Node To Connect To
  packages/light-apps/package.json
  packages/light-apps/src/Content/Content.tsx
  packages/light-apps/src/IdentityHeader/IdentityHeader.tsx
  packages/ui-common/src/ContextGate.tsx
  yarn.lock
Labels: A8-looksgood

#308 feat(electron-app): Bundle Parity Substrate
  .gitignore
  .travis.yml
  getSubstrate.sh
  package.json
  packages/electron-app/package.json
  packages/electron-app/src/main/app/constants/index.ts
  packages/electron-app/src/main/index.ts
  packages/electron-app/src/main/util/csp.ts
  packages/electron-app/src/main/util/index.ts
  packages/electron-app/src/main/util/isSubstrateRunning.ts
  packages/electron-app/src/main/util/staticPath.ts
  packages/electron-app/src/main/util/substrateProcess.ts
  scripts/fetchLatestSubstrate.js
  yarn.lock
Labels: @electron-app, A8-looksgood

#316 fix(electron-app): Make the binary work correctly
  packages/electron-app/src/main/app/constants.ts
  packages/electron-app/src/main/app/menu.ts
  packages/electron-app/src/main/index.ts
  packages/electron-app/src/main/util/substrateProcess.ts
  packages/light-apps/src/App.tsx
  packages/ui-common/src/ContextGate.tsx
Labels: A0-pleasereview

#320 chore: Switch to gitlab
  .gitlab-ci.yml
  .travis.yml
Labels: A8-looksgood

#334 chore: Remove build scripts from CI
  .gitlab-ci.yml
  getSubstrate.sh
Labels: A0-pleasereview

#319 chore: Update README.md
  README.md
Labels: A8-looksgood

#337 chore: Update README.md
  README.md
Labels: A0-pleasereview, A2-insubstantial

#338 Update link to Substrate docs in readme
  README.md
Labels: A8-looksgood

#339 refactor: Remove <Subscribe>, use hooks
  packages/light-apps/src/Content/Content.tsx
  packages/light-apps/src/SavedAddresses.tsx
  packages/transfer-app/src/Transfer.tsx
  packages/ui-common/src/Subscribe.tsx
  packages/ui-common/src/index.ts
  packages/ui-components/src/stateful/Balance.tsx
Labels: A8-looksgood

#345 chore(electron-app): Update to Electron 5
  packages/electron-app/package.json
  packages/electron-app/src/main/app/menu.ts
  packages/electron-app/src/main/index.ts
  yarn.lock
Labels: A0-pleasereview

#346 refactor(electron-app): Use winston instead of pino
  packages/electron-app/package.json
  packages/electron-app/src/main/app/isSubstrateRunning.ts
  packages/electron-app/src/main/app/menu.ts
  packages/electron-app/src/main/app/substrateProcess.ts
  packages/electron-app/src/main/index.ts
  packages/electron-app/src/main/util/declarations/pino.d.ts
  packages/electron-app/src/main/util/index.ts
  packages/electron-app/src/main/util/logger.ts
  packages/electron-app/src/main/util/substrateProcess.ts
  yarn.lock
Labels: A8-looksgood

#335 feat(governance-app): View Proposals and Referendums
  .gitignore
  lerna.json
  packages/electron-app/package.json
  packages/governance-app/README.md
  packages/governance-app/package.json
  packages/governance-app/src/Democracy.tsx
  packages/governance-app/src/Governance.tsx
  packages/governance-app/src/ProposalRow.tsx
  packages/governance-app/src/Proposals.tsx
  packages/governance-app/src/Referenda.tsx
  packages/governance-app/src/ReferendumRow.tsx
  packages/governance-app/src/index.ts
  packages/governance-app/tsconfig.json
  packages/light-apps/package.json
  packages/light-apps/src/Content/Content.tsx
  packages/light-apps/src/IdentityHeader/IdentityHeader.tsx
  packages/transfer-app/package.json
  packages/ui-common/package.json
  packages/ui-components/package.json
  packages/ui-components/src/Progress.tsx
  packages/ui-components/src/Shared.styles.ts
  packages/ui-components/src/YayNay.tsx
  packages/ui-components/src/globalStyle.tsx
  packages/ui-components/src/index.ts
  packages/ui-components/src/stateful/AddressSummary/AddressSummary.tsx
  packages/ui-components/src/types.ts
  packages/ui-components/stories/Buttons.stories.tsx
  packages/ui-components/stories/Progress.stories.tsx
  packages/ui-components/stories/YayNay.stories.tsx
  packages/ui-components/stories/customDecorators/withTheme.tsx
  scripts/prestart.sh
  yarn.lock
Labels: A8-looksgood

#355 refactor: Use function components, remove React class
  packages/light-apps/src/AddAccount/AddAccount.tsx
  packages/light-apps/src/AddAccount/Create.tsx
  packages/light-apps/src/AddAccount/ImportWithPhrase.tsx
  packages/light-apps/src/AddAccount/Restore.tsx
  packages/light-apps/src/Alerts/Alerts.tsx
  packages/light-apps/src/App.tsx
  packages/light-apps/src/ManageAddresses/Add.tsx
  packages/light-apps/src/ManageAddresses/Edit.tsx
  packages/light-apps/src/ManageAddresses/ManageAddresses.tsx
  packages/light-apps/src/ManageAddresses/SaveAddress/SaveAddress.tsx
  packages/light-apps/src/ManageAddresses/SavedAddresses.tsx
  packages/light-apps/src/Onboarding/CreateNewAccountScreen.tsx
  packages/light-apps/src/Onboarding/ImportOptionsScreen.tsx
  packages/light-apps/src/Onboarding/ImportWithJson.tsx
  packages/light-apps/src/Onboarding/ImportWithPhrase.tsx
  packages/light-apps/src/Onboarding/Onboarding.tsx
  packages/light-apps/src/Onboarding/SaveScreen.tsx
  packages/light-apps/src/TopBar/TopBar.styles.tsx
  packages/light-apps/src/index.tsx
  packages/transfer-app/src/SendBalance/Validation.tsx
  packages/transfer-app/src/TxQueue.tsx
  packages/ui-common/src/ContextGate.tsx
  packages/ui-components/src/Address.tsx
  packages/ui-components/src/BalanceDisplay.tsx
  packages/ui-components/src/Card.tsx
  packages/ui-components/src/CopyButton.tsx
  packages/ui-components/src/Grid.tsx
  packages/ui-components/src/Labelled.tsx
  packages/ui-components/src/Loading.tsx
  packages/ui-components/src/Margin.tsx
  packages/ui-components/src/MnemonicSegment.tsx
  packages/ui-components/src/Modal.tsx
  packages/ui-components/src/NavButton.tsx
  packages/ui-components/src/NavLink.tsx
  packages/ui-components/src/Progress.tsx
  packages/ui-components/src/TextArea.tsx
  packages/ui-components/src/WalletCard.tsx
  packages/ui-components/src/YayNay.tsx
  packages/ui-components/src/index.ts
  packages/ui-components/src/stateful/AddressSummary/AddressSummary.tsx
Labels: A0-pleasereview

#356 refactor: Attempt to fix CodeClimate score
  packages/governance-app/src/ProposalRow.tsx
  packages/light-apps/src/AddAccount/AddAccount.tsx
  packages/light-apps/src/AddAccount/Create.tsx
  packages/light-apps/src/AddAccount/ImportWithJson.tsx
  packages/light-apps/src/AddAccount/ImportWithPhrase.tsx
  packages/light-apps/src/App.tsx
  packages/light-apps/src/IdentityHeader/Backup.tsx
  packages/light-apps/src/IdentityHeader/Forget.tsx
  packages/light-apps/src/IdentityHeader/IdentityHeader.tsx
  packages/light-apps/src/IdentityHeader/Rename.tsx
  packages/light-apps/src/ManageAddresses/SaveAddress/SaveAddress.tsx
  packages/light-apps/src/TopBar/TopBar.styles.tsx
  packages/light-apps/src/TxQueueNotifier/TxQueueNotifier.tsx
  packages/transfer-app/src/SendBalance/SendBalance.tsx
  packages/transfer-app/src/SendBalance/validate.ts
  packages/transfer-app/src/TxQueue.tsx
  packages/ui-common/src/TxQueueContext.tsx
  packages/ui-common/src/index.ts
  packages/ui-common/src/util/index.ts
  packages/ui-common/src/util/keyring.ts
  packages/ui-common/src/util/ui.tsx
  packages/ui-components/src/TxSummary.tsx
  packages/ui-components/src/stateful/AddressSummary/AddressSummary.tsx
Labels: A8-looksgood
