Repository paritytech/substrate-light-ui, pull requests merged in 2019-06, with the labels that each got.

#374 fix: Revert #368 and fix lint bug
  yarn.lock
Labels: A0-pleasereview, M5-dependencies

#352 feat(governance-app): Council
  packages/governance-app/src/Council/Council.tsx
  packages/governance-app/src/Council/CouncilCandidates.tsx
  packages/governance-app/src/Council/CouncilMembers.tsx
  packages/governance-app/src/Council/CouncilSummary.tsx
  packages/governance-app/src/Council/index.tsx
  packages/governance-app/src/Democracy/Democracy.tsx
  packages/governance-app/src/Democracy/ProposalRow.tsx
  packages/governance-app/src/Democracy/Proposals.tsx
  packages/governance-app/src/Democracy/Referenda.tsx
  packages/governance-app/src/Democracy/ReferendumRow.tsx
  packages/governance-app/src/Democracy/index.ts
  packages/governance-app/src/Governance.tsx
  packages/light-apps/src/TopBar/TopBar.styles.tsx
  yarn.lock
Labels: A8-looksgood

#389 chore: Update all @polkadot/* packages
  package.json
  packages/governance-app/src/Democracy/Referenda.tsx
  packages/light-apps/package.json
  packages/ui-common/package.json
  packages/ui-components/package.json
  yarn.lock
Labels: A0-pleasereview

#391 chore: Update axios
  packages/electron-app/package.json
  packages/electron-app/src/main/app/isSubstrateRunning.ts
  yarn.lock
Labels: A8-looksgood
