Repository paritytech/substrate-light-ui, pull requests merged in 2019-04, with the labels that each got.

#232 bump @polkadot/api to 0.75.1
  packages/light-apps/src/IdentityCard/IdentityCard.tsx
  packages/transfer-app/src/SentBalance.tsx
  packages/ui-api/package.json
  yarn.lock
Labels: @transfer-app, A8-looksgood, M5-dependencies

#222 fix: Ignore ELECTRON_START_URL in production
  packages/electron-app/src/main/index.ts
  packages/electron-app/src/main/util/staticPath.ts
Labels: A8-looksgood

#235 fix(ui-components): remove min-height: 100%; from Stacked
  packages/ui-components/src/Shared.styles.ts
Labels: @ui-components, A8-looksgood

#247 feat(transfer-app): Send Balance new mockup
  packages/light-apps/package.json
  packages/light-apps/src/Content/Content.tsx
  packages/transfer-app/src/Saved.tsx
  packages/transfer-app/src/SendBalance.tsx
  packages/transfer-app/src/SentBalance.tsx
  packages/transfer-app/src/Transfer.styles.tsx
  packages/transfer-app/src/Transfer.tsx
  packages/transfer-app/src/index.ts
  packages/transfer-app/src/types.ts
  packages/ui-api/src/Subscribe.tsx
  packages/ui-components/package.json
  packages/ui-components/src/Accordion.tsx
  packages/ui-components/src/Address.tsx
  packages/ui-components/src/AddressSummary/AddressSummary.tsx
  packages/ui-components/src/AddressSummary/index.ts
  packages/ui-components/src/AddressSummary/index.tsx
  packages/ui-components/src/Balance.tsx
  packages/ui-components/src/Card.tsx
  packages/ui-components/src/CopyButton.tsx
  packages/ui-components/src/FlexSegment.tsx
  packages/ui-components/src/Grid.tsx
  packages/ui-components/src/Icon.tsx
  packages/ui-components/src/InputFile.tsx
  packages/ui-components/src/Labelled.tsx
  packages/ui-components/src/Loading.tsx
  packages/ui-components/src/Margin.tsx
  packages/ui-components/src/Menu.tsx
  packages/ui-components/src/MnemonicSegment.tsx
  packages/ui-components/src/Modal.tsx
  packages/ui-components/src/NavButton.tsx
  packages/ui-components/src/NavLink.tsx
  packages/ui-components/src/Shared.styles.ts
  packages/ui-components/src/StyleProps.tsx
  packages/ui-components/src/TextArea.tsx
  packages/ui-components/src/WalletCard.tsx
  packages/ui-components/src/index.ts
  packages/ui-components/src/types.ts
  packages/ui-components/stories/Address.stories.tsx
  packages/ui-components/stories/AddressSummary.stories.tsx
  packages/ui-components/stories/Input.stories.tsx
  packages/ui-components/stories/NavButton.stories.tsx
  packages/ui-components/stories/NavLink.stories.tsx
  packages/ui-components/stories/WalletCard.stories.tsx
  yarn.lock
Labels: A0-pleasereview

#252 chore(deps): Bump api, ui-api, ui-signer
  packages/ui-api/package.json
  packages/ui-components/package.json
  yarn.lock
Labels: M5-dependencies

#233 fix: Rework Identity App
  packages/identity-app/README.md
  packages/identity-app/src/Create.tsx
  packages/identity-app/src/Edit.tsx
  packages/identity-app/src/Identity.tsx
  packages/identity-app/src/ImportWithJson.tsx
  packages/identity-app/src/ImportWithPhrase.tsx
  packages/identity-app/src/ManageAccounts.tsx
  packages/identity-app/src/ManageAddresses.tsx
  packages/identity-app/src/Restore.tsx
  packages/identity-app/src/SaveAddress.tsx
  packages/identity-app/src/SavedAccounts.tsx
  packages/identity-app/src/SavedAddresses.tsx
  packages/identity-app/src/Wallet.tsx
  packages/identity-app/src/types.ts
  packages/light-apps/src/IdentityCard/IdentityCard.tsx
  packages/light-apps/src/Onboarding/CreateNewAccountScreen.tsx
  packages/light-apps/src/Onboarding/ImportWithJson.tsx
  packages/light-apps/src/Onboarding/ImportWithPhrase.tsx
  packages/light-apps/src/Onboarding/SaveScreen.tsx
  packages/transfer-app/src/Transfer.tsx
  packages/ui-components/src/InputFile.tsx
  packages/ui-components/stories/Menu.stories.tsx
  packages/ui-components/stories/theme.stories.tsx
Labels: A8-looksgood

#253 feat: Add app-wide alerts
  packages/identity-app/package.json
  packages/identity-app/src/Create.tsx
  packages/identity-app/src/Edit.tsx
  packages/identity-app/src/ImportWithJson.tsx
  packages/identity-app/src/ImportWithPhrase.tsx
  packages/identity-app/src/SaveAddress.tsx
  packages/identity-app/src/SavedAccounts.tsx
  packages/identity-app/src/SavedAddresses.tsx
  packages/light-apps/package.json
  packages/light-apps/src/Alerts/Alerts.tsx
  packages/light-apps/src/Alerts/index.ts
  packages/light-apps/src/App.tsx
  packages/light-apps/src/Content/Content.tsx
  packages/light-apps/src/IdentityCard/IdentityCard.tsx
  packages/light-apps/src/Onboarding/CreateNewAccountScreen.tsx
  packages/light-apps/src/Onboarding/SaveScreen.tsx
  packages/transfer-app/package.json
  packages/transfer-app/src/SendBalance.tsx
  packages/transfer-app/src/SentBalance.tsx
  packages/ui-api/src/ApiContext.tsx
  packages/ui-api/src/ApiGate.tsx
  packages/ui-api/src/util/index.ts
  packages/ui-api/src/util/isTestChain.ts
  packages/ui-common/LICENSE
  packages/ui-common/README.md
  packages/ui-common/package.json
  packages/ui-common/src/AppContext.tsx
  packages/ui-common/src/ContextGate.tsx
  packages/ui-common/src/Subscribe.tsx
  packages/ui-common/src/alerts/alerts.ts
  packages/ui-common/src/alerts/index.ts
  packages/ui-common/src/index.ts
  packages/ui-common/src/util/index.ts
  packages/ui-common/src/util/isTestChain.ts
  packages/ui-common/tsconfig.json
  packages/ui-components/src/Alert.tsx
  packages/ui-components/src/Loading.tsx
  packages/ui-components/src/NavLink.tsx
  packages/ui-components/src/Shared.styles.ts
  packages/ui-components/src/StyleProps.tsx
  packages/ui-components/src/index.ts
  scripts/prestart.sh
  yarn.lock
Labels: A0-pleasereview

#261 refactor: Create a `<Balance>` component
  packages/identity-app/src/SavedAccounts.tsx
  packages/identity-app/src/SavedAddresses.tsx
  packages/light-apps/src/IdentityHeader/IdentityHeader.tsx
  packages/transfer-app/src/SendBalance.tsx
  packages/ui-components/package.json
  packages/ui-components/src/Balance.tsx
  packages/ui-components/src/BalanceDisplay.tsx
  packages/ui-components/src/Margin.tsx
  packages/ui-components/src/NavButton.tsx
  packages/ui-components/src/NavLink.tsx
  packages/ui-components/src/Shared.styles.ts
  packages/ui-components/src/StyleProps.tsx
  packages/ui-components/src/WalletCard.tsx
  packages/ui-components/src/constants.ts
  packages/ui-components/src/index.ts
  packages/ui-components/src/stateful/AddressSummary/AddressSummary.styles.ts
  packages/ui-components/src/stateful/AddressSummary/AddressSummary.tsx
  packages/ui-components/src/stateful/AddressSummary/index.ts
  packages/ui-components/src/stateful/AddressSummary/types.ts
  packages/ui-components/src/stateful/Balance.tsx
  packages/ui-components/src/stateful/index.ts
  packages/ui-components/src/types.ts
  packages/ui-components/stories/AddressSummary.stories.tsx
  packages/ui-components/stories/NavButton.stories.tsx
  packages/ui-components/stories/NavLink.stories.tsx
  packages/ui-components/stories/theme.stories.tsx
  scripts/prestart.sh
Labels: A8-looksgood

#262 Rework UX
  packages/identity-app/LICENSE
  packages/identity-app/README.md
  packages/identity-app/package.json
  packages/identity-app/src/Identity.tsx
  packages/identity-app/src/ManageAccounts/Edit.tsx
  packages/identity-app/src/ManageAccounts/ManageAccounts.tsx
  packages/identity-app/src/ManageAccounts/index.ts
  packages/identity-app/src/ManageAddresses/ManageAddresses.tsx
  packages/identity-app/src/SavedAccounts.tsx
  packages/identity-app/tsconfig.json
  packages/light-apps/package.json
  packages/light-apps/src/AddAccount/AddAccount.tsx
  packages/light-apps/src/AddAccount/Create.tsx
  packages/light-apps/src/AddAccount/ImportWithJson.tsx
  packages/light-apps/src/AddAccount/ImportWithPhrase.tsx
  packages/light-apps/src/AddAccount/Restore.tsx
  packages/light-apps/src/AddAccount/index.tsx
  packages/light-apps/src/App.tsx
  packages/light-apps/src/Content/Content.tsx
  packages/light-apps/src/IdentityHeader/IdentityHeader.styles.tsx
  packages/light-apps/src/IdentityHeader/IdentityHeader.tsx
  packages/light-apps/src/ManageAddresses/Add.tsx
  packages/light-apps/src/ManageAddresses/Edit.tsx
  packages/light-apps/src/ManageAddresses/ManageAddresses.tsx
  packages/light-apps/src/ManageAddresses/SaveAddress/SaveAddress.tsx
  packages/light-apps/src/ManageAddresses/SaveAddress/index.ts
  packages/light-apps/src/ManageAddresses/index.ts
  packages/light-apps/src/Onboarding/CreateNewAccountScreen.tsx
  packages/light-apps/src/SavedAddresses.tsx
  packages/light-apps/src/TopBar/TopBar.styles.tsx
  packages/light-apps/src/TopBar/TopBar.tsx
  packages/light-apps/src/TopBar/index.tsx
  packages/light-apps/src/TopBar/types.ts
  packages/transfer-app/src/SendBalance.tsx
  packages/transfer-app/src/Transfer.tsx
  packages/ui-common/src/Subscribe.tsx
  scripts/prestart.sh
Labels: A8-looksgood

#271 Block UI when disconnected (close #217)
  packages/light-apps/src/App.tsx
  packages/ui-common/src/ContextGate.tsx
  packages/ui-components/src/Loading.tsx
Labels: A8-looksgood

#270 Prettify various holes in the UI
  packages/light-apps/src/AddAccount/AddAccount.tsx
  packages/light-apps/src/AddAccount/Create.tsx
  packages/light-apps/src/AddAccount/ImportWithJson.tsx
  packages/light-apps/src/AddAccount/ImportWithPhrase.tsx
  packages/light-apps/src/AddAccount/Restore.tsx
  packages/light-apps/src/Content/Content.tsx
  packages/light-apps/src/IdentityHeader/IdentityHeader.tsx
  packages/light-apps/src/ManageAddresses/SaveAddress/SaveAddress.tsx
  packages/light-apps/src/Onboarding/ImportWithJson.tsx
  packages/light-apps/src/SavedAddresses.tsx
  packages/light-apps/src/TopBar/TopBar.tsx
  packages/transfer-app/src/SendBalance.tsx
  packages/transfer-app/src/Transfer.tsx
  packages/ui-common/src/Subscribe.tsx
  packages/ui-components/src/Alert.tsx
  packages/ui-components/src/BalanceDisplay.tsx
  packages/ui-components/src/InputFile.tsx
  packages/ui-components/src/Shared.styles.ts
  packages/ui-components/src/StyleProps.tsx
  packages/ui-components/src/constants.ts
  packages/ui-components/src/globalStyle.tsx
  packages/ui-components/src/index.ts
  packages/ui-components/src/stateful/AddressSummary/AddressSummary.tsx
  packages/ui-components/src/types.ts
  packages/ui-components/stories/Alert.stories.tsx
  packages/ui-components/stories/InputFile.stories.tsx
Labels: A8-looksgood

#273 feat(transfer-app): Calculate fees before sending tx
  packages/transfer-app/package.json
  packages/transfer-app/src/SendBalance/SendBalance.tsx
  packages/transfer-app/src/SendBalance/Validation.tsx
  packages/transfer-app/src/SendBalance/index.ts
  packages/transfer-app/src/SendBalance/types.ts
  packages/transfer-app/src/SendBalance/validate.ts
  packages/transfer-app/src/SentBalance.tsx
  packages/transfer-app/src/Transfer.tsx
  packages/ui-components/package.json
  packages/ui-components/src/index.ts
  yarn.lock
Labels: A8-looksgood

#279 Make header show on all routes
  packages/light-apps/src/AddAccount/AddAccount.tsx
  packages/light-apps/src/AddAccount/Create.tsx
  packages/light-apps/src/AddAccount/ImportWithJson.tsx
  packages/light-apps/src/AddAccount/ImportWithPhrase.tsx
  packages/light-apps/src/AddAccount/Restore.tsx
  packages/light-apps/src/Alerts/Alerts.tsx
  packages/light-apps/src/App.tsx
  packages/light-apps/src/Content/Content.tsx
  packages/light-apps/src/IdentityHeader/IdentityHeader.tsx
  packages/light-apps/src/ManageAddresses/Add.tsx
  packages/light-apps/src/ManageAddresses/Edit.tsx
  packages/light-apps/src/ManageAddresses/ManageAddresses.tsx
  packages/light-apps/src/ManageAddresses/SaveAddress/SaveAddress.tsx
  packages/light-apps/src/Onboarding/CreateNewAccountScreen.tsx
  packages/light-apps/src/Onboarding/ImportOptionsScreen.tsx
  packages/light-apps/src/Onboarding/ImportWithJson.tsx
  packages/light-apps/src/Onboarding/ImportWithPhrase.tsx
  packages/light-apps/src/Onboarding/Onboarding.tsx
  packages/light-apps/src/Onboarding/SaveScreen.tsx
  packages/light-apps/src/SavedAddresses.tsx
  packages/light-apps/src/TopBar/TopBar.tsx
  packages/transfer-app/src/Transfer.styles.tsx
  packages/transfer-app/src/Transfer.tsx
  packages/ui-common/src/ContextGate.tsx
  yarn.lock
Labels: A0-pleasereview

#292 AlertsContext and TxQueueContext; CRA3 & React hooks
  packages/light-apps/package.json
  packages/light-apps/src/AddAccount/ImportWithJson.tsx
  packages/light-apps/src/Alerts/Alerts.tsx
  packages/light-apps/src/App.tsx
  packages/light-apps/src/IdentityHeader/IdentityHeader.tsx
  packages/light-apps/src/Onboarding/ImportWithJson.tsx
  packages/light-apps/src/TopBar/TopBar.tsx
  packages/light-apps/src/TxQueueNotifier/TxQueueNotifier.tsx
  packages/light-apps/src/TxQueueNotifier/index.ts
  packages/transfer-app/src/SendBalance/SendBalance.tsx
  packages/transfer-app/src/SentBalance.tsx
  packages/transfer-app/src/Transfer.tsx
  packages/transfer-app/src/TxQueue.tsx
  packages/ui-common/package.json
  packages/ui-common/src/AlertsContext.tsx
  packages/ui-common/src/AppContext.tsx
  packages/ui-common/src/ContextGate.tsx
  packages/ui-common/src/TxQueueContext.tsx
  packages/ui-common/src/alerts/alerts.ts
  packages/ui-common/src/index.ts
  packages/ui-components/package.json
  tsconfig.json
  yarn.lock
Labels: A8-looksgood

#300 Add ability to copy address in header and address book
  packages/light-apps/src/IdentityHeader/IdentityHeader.tsx
  packages/light-apps/src/SavedAddresses.tsx
  packages/ui-components/src/CopyButton.tsx
  packages/ui-components/src/index.ts
Labels: A8-looksgood

#303 Improve CSP
  packages/electron-app/src/main/index.ts
  packages/electron-app/src/main/util/csp.ts
  packages/light-apps/public/index.html
Labels: A0-pleasereview

#278 Implement Electron Security Guidelines
  packages/electron-app/README.md
  packages/electron-app/package.json
  packages/electron-app/src/main/index.ts
  packages/electron-app/src/main/util/constants.ts
  packages/electron-app/src/main/util/csp.ts
  packages/electron-app/src/main/util/declarations/pino.d.ts
  packages/electron-app/src/main/util/index.ts
  packages/light-apps/public/index.html
  packages/light-apps/public/manifest.json
  yarn.lock
Labels: @electron-app, A8-looksgood
