Repository paritytech/substrate-light-ui, pull requests merged in 2019-02, with the labels that each got.

#46 Prestart: yarn build
  package.json
  scripts/prestart.sh
Labels: A8-looksgood

#45 Rename and update packages
  packages/electron-app/package.json
  packages/electron-app/src/main/index.ts
  packages/identity-app/package.json
  packages/identity-app/src/AddressBook.tsx
  packages/identity-app/src/Identity.tsx
  packages/identity-app/src/SavedAccounts.tsx
  packages/identity-app/src/Wallet.tsx
  packages/light-apps/package.json
  packages/light-apps/src/App.tsx
  packages/light-apps/src/Content/Content.tsx
  packages/light-apps/src/IdentityCard/IdentityCard.tsx
  packages/light-apps/src/Onboarding/CreateNewAccountScreen.tsx
  packages/light-apps/src/Onboarding/ImportOptionsScreen.tsx
  packages/light-apps/src/Onboarding/ImportWithJson.tsx
  packages/light-apps/src/Onboarding/ImportWithPhrase.tsx
  packages/light-apps/src/Onboarding/Onboarding.tsx
  packages/light-apps/src/Onboarding/SaveScreen.tsx
  packages/transfer-app/package.json
  packages/transfer-app/src/Saved.tsx
  packages/transfer-app/src/SendBalance.tsx
  packages/transfer-app/src/Transfer.tsx
  packages/ui-api/package.json
  packages/ui-components/package.json
  packages/ui-components/src/AddressSummary/AddressSummary.styles.ts
  packages/ui-components/src/AddressSummary/AddressSummary.tsx
  packages/ui-components/src/CopyButton.tsx
  packages/ui-components/src/InputFile.tsx
  packages/ui-components/src/Labelled.tsx
  packages/ui-components/src/Modal.tsx
  packages/ui-components/src/util/toAddress.ts
  packages/ui-components/src/util/toShortAddress.ts
  yarn.lock
Labels: A0-pleasereview

#51 Remove isFirstRun
  packages/light-apps/package.json
  packages/light-apps/src/App.tsx
  packages/light-apps/src/Content/Content.tsx
  packages/light-apps/src/IdentityCard/IdentityCard.tsx
  packages/light-apps/src/Onboarding/CreateNewAccountScreen.tsx
  packages/light-apps/src/Onboarding/SaveScreen.tsx
  packages/light-apps/src/stores/index.ts
  packages/light-apps/src/stores/onboardingStore.ts
  packages/ui-api/package.json
  packages/ui-components/package.json
  yarn.lock
Labels: A8-looksgood

#49 use observables for displaying accounts & addresses
  packages/identity-app/src/SavedAccounts.tsx
  packages/identity-app/src/Wallet.tsx
  packages/light-apps/src/IdentityCard/IdentityCard.tsx
  packages/transfer-app/src/Saved.tsx
  packages/transfer-app/src/SendBalance.tsx
  yarn.lock
Labels: A7-looksgoodcantmerge, A8-looksgood

#53 Package electron
  README.md
  package.json
  packages/electron-app/README.md
  packages/electron-app/electron-builder.json
  packages/electron-app/package.json
  packages/electron-app/src/main/index.ts
  packages/electron-app/src/main/util/staticPath.ts
  packages/identity-app/package.json
  packages/light-apps/package.json
  packages/transfer-app/package.json
  packages/ui-api/package.json
  packages/ui-components/package.json
  yarn.lock
Labels: A8-looksgood

#56 Send Balance
  packages/identity-app/src/SavedAccounts.tsx
  packages/light-apps/src/IdentityCard/IdentityCard.tsx
  packages/transfer-app/src/Saved.tsx
  packages/transfer-app/src/SendBalance.tsx
  packages/ui-api/src/ApiGate.tsx
  packages/ui-api/src/util/index.ts
  packages/ui-api/src/util/isTestChain.ts
  packages/ui-components/src/AddressSummary/AddressSummary.tsx
Labels: A0-pleasereview

#66 rewrite recovery phrase
  packages/identity-app/src/Create.tsx
  packages/light-apps/src/IdentityCard/IdentityCard.tsx
  packages/light-apps/src/Onboarding/CreateNewAccountScreen.tsx
  packages/transfer-app/src/SendBalance.tsx
  packages/ui-api/src/ApiGate.tsx
  packages/ui-components/src/TextArea.tsx
  packages/ui-components/src/index.ts
Labels: @light-apps, F8-enhancement
